name: build and release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3
        
      - name: Check Out
        run: chmod +x build.sh
        
      - name: Build
        run: ./build.sh d2x N
        
      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/build/
